[package]
name = "troika_rust"
version = "0.1.0"
authors = ["Yu Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "troika_benchmark"
harness = false
